//! Algebraic effect data plane for plugins (ADR-053).
//!
//! This module ships the type-level scaffolding that the `define_plugin!`
//! macro lowers `effects on <Trigger> { yield Effect::X(...) }` blocks onto:
//! the [`Effectful`] trait, the [`EffectSet`] projection from effect set to
//! manifest capabilities, the [`Yielder`] single-shot continuation
//! interface, and the [`Effect`] taxonomy itself.
//!
//! The host-side dispatch path (capability subset check, mock harness, real
//! handler), the macro front-end, and the bundled-plugin migration land in
//! later ADR-053 chunks. Chunk 1 ships these signatures so dependent code
//! can compile against stable trait shapes.

use core::fmt;

/// Stable identifier for a host capability declared in a plugin's
/// `kasane-plugin.toml` manifest.
///
/// Strings are the manifest's `[capabilities]` table keys:
/// - `"filesystem"`, `"environment"`, `"monotonic-clock"`, `"process"` —
///   WASI surfaces (matching `kasane:plugin@6.5.0` `capability` ordinals
///   in [`crate::capability`]).
/// - A service name (e.g. `"open-buffer-view"`) for ADR-052 capability
///   resources.
///
/// The set is open: chunks 2–5 of ADR-053 add capabilities as the
/// [`Effect`] taxonomy grows.
#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub struct CapabilityName(pub &'static str);

impl CapabilityName {
    /// The capability identifier string.
    pub const fn as_str(&self) -> &'static str {
        self.0
    }
}

impl fmt::Debug for CapabilityName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "CapabilityName({:?})", self.0)
    }
}

impl fmt::Display for CapabilityName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.0)
    }
}

mod sealed {
    pub trait Sealed {}
}

/// Sealed marker preventing external [`EffectSet`] implementations.
///
/// `define_plugin!` is the only sanctioned source of `EffectSet` impls so
/// the capability-subset proof remains macro-derived. External plugins
/// cannot fabricate an `EffectSet` whose `REQUIRED_CAPABILITIES` disagrees
/// with the effects they actually yield.
pub use sealed::Sealed;

/// Compile-time projection from a plugin's effect set onto the host
/// capabilities required to yield any effect in that set.
///
/// Implementations are sealed; the only intended implementor is the
/// `__KasaneEffectSet` marker type generated by `define_plugin!` from the
/// union of `yield Effect::X(...)` sites. `REQUIRED_CAPABILITIES` is
/// computed at compile time. Chunk 3 of ADR-053 emits a `const_assert`
/// that this slice is a subset of the manifest's declared capabilities;
/// chunk 4 plumbs the same projection into the mock-handler harness so
/// `MockHandler::reject(...)` can refuse effects that lack manifest
/// authority.
pub trait EffectSet: Sealed {
    /// Concrete yielder produced by `define_plugin!` for this effect set.
    /// Holds the CPS trampoline state for handlers lowered from
    /// `effects on Trigger { ... }` blocks.
    type Yielder: Yielder;

    /// Static set of capabilities required to yield any effect in this
    /// set. Computed by the macro from the union of `yield Effect::X(...)`
    /// sites.
    const REQUIRED_CAPABILITIES: &'static [CapabilityName];
}

/// Single-shot effect yielder.
///
/// A plugin emits an effect via [`Yielder::emit`], the host returns either
/// a typed reply or a rejection, and the plugin resumes exactly once. No
/// multi-shot semantics (ADR-053 §Scope: AI tree-search / rollback live
/// outside the plugin path).
pub trait Yielder {
    /// The effect alphabet this yielder accepts.
    type Effect;
    /// The reply produced for a successfully dispatched effect.
    type Reply;
    /// The failure produced when the host rejects an effect — typically a
    /// manifest capability mismatch, an explicit host rejection, or a
    /// mock-handler-induced fault during tests.
    type Error;

    /// Emit an effect; block until the host returns a reply.
    ///
    /// In the wasm32 guest the call lowers to a host import (no actual
    /// blocking from the guest's perspective; the host scheduler suspends
    /// the component). On the host or in tests, the call dispatches
    /// against the active effect handler (real runtime or [`MockHandler`]
    /// from the test harness, landing in chunk 4).
    fn emit(&mut self, effect: Self::Effect) -> Result<Self::Reply, Self::Error>;
}

/// Outcome of a single [`Effectful::step`] call.
#[derive(Debug, PartialEq, Eq)]
pub enum EffectfulResult {
    /// The trigger has been fully serviced; no further yields until the
    /// next trigger fires.
    Done,
    /// The plugin received a terminal `Err` from the yielder (host
    /// rejection or capability mismatch) and could not recover. The host
    /// is expected to surface the failure through the diagnostic channel
    /// (ADR-033) and continue without quarantining the plugin.
    Aborted,
}

/// Plugins that participate in algebraic-effect dispatch implement this
/// trait via the `define_plugin!` macro's `effects on <Trigger> { ... }`
/// block (chunk 2).
///
/// `step()` runs the handler body for a single trigger, emitting effects
/// through the yielder. The macro CPS-lowers the block to a state machine
/// that drives this method; plugin authors never implement `Effectful`
/// by hand.
pub trait Effectful {
    /// The effect alphabet this plugin yields. The macro generates a
    /// marker type implementing [`EffectSet`].
    type Effects: EffectSet;

    /// Run one step of the effect machine.
    fn step(&mut self, yielder: &mut <Self::Effects as EffectSet>::Yielder) -> EffectfulResult;
}

/// Plugin-yieldable side effects.
///
/// The chunk 1 starter set covers the most common host commands. Chunks
/// 2–5 expand the variant set to mirror every plugin-reachable WIT
/// `command` case and the ADR-052 capability-resource calls.
///
/// Variants are `#[non_exhaustive]`-style additive — adding a new variant
/// is **not** a breaking change for plugins that did not name it in a
/// `yield` site, because `define_plugin!` derives
/// [`EffectSet::REQUIRED_CAPABILITIES`] from the *used* variants only.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Effect {
    /// Request a redraw of the surface containing the plugin's UI.
    /// Mirrors WIT `command::request-redraw(u16)`.
    Redraw(u16),

    /// Evaluate a Kakoune command in the active session (ADR-041).
    /// Mirrors WIT `command::eval-command(string)`.
    EvalCommand(String),

    /// Set the system clipboard contents.
    /// Mirrors WIT `command::set-clipboard(string)`.
    SetClipboard(String),

    /// Paste text from the system clipboard. The reply carries the pasted
    /// text. Mirrors WIT `command::paste-clipboard`.
    PasteClipboard,
}

impl Effect {
    /// Capabilities required to yield this effect.
    ///
    /// Returns a `'static` slice so the macro-generated
    /// [`EffectSet::REQUIRED_CAPABILITIES`] can union slices across yield
    /// sites without allocation.
    ///
    /// Talking to Kakoune is **implicit** — every plugin already runs
    /// inside a Kakoune frontend session, so `EvalCommand` and friends
    /// require no manifest declaration. Effects that reach a host
    /// *service* (clipboard, network, FS) name that service so the
    /// macro can cross-check against the manifest.
    pub fn required_capabilities(&self) -> &'static [CapabilityName] {
        match self {
            Effect::Redraw(_) | Effect::EvalCommand(_) => &[],
            Effect::SetClipboard(_) | Effect::PasteClipboard => &[CapabilityName("clipboard")],
        }
    }
}

/// Reply carried back from the host for a successful [`Effect`] dispatch.
///
/// The variant tag must match the [`Effect`] variant the plugin emitted.
/// The macro lowers `let x = yield Effect::PasteClipboard` to a `match`
/// on this enum that unwraps the appropriate field; mismatched tags are
/// a host-side bug.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EffectReply {
    /// Fire-and-forget reply for effects with no return value (`Redraw`,
    /// `EvalCommand`, `SetClipboard`).
    Unit,
    /// Pasted clipboard text returned for `Effect::PasteClipboard`.
    ClipboardText(String),
}

/// Failure produced by [`Yielder::emit`].
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EffectError {
    /// The plugin's manifest does not declare a capability that the effect
    /// requires. Surfaced at runtime when chunk 3's compile-time check is
    /// bypassed (e.g. a plugin built against an older SDK than the host).
    MissingCapability(CapabilityName),
    /// The host explicitly rejected the effect — for instance, a mock
    /// handler configured with `.reject(...)` (chunk 4), or a runtime
    /// authority decision (`InjectInput` from a tier-3 handler).
    Rejected(&'static str),
}

impl fmt::Display for EffectError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EffectError::MissingCapability(cap) => {
                write!(f, "missing capability: {cap}")
            }
            EffectError::Rejected(reason) => {
                write!(f, "effect rejected: {reason}")
            }
        }
    }
}

impl std::error::Error for EffectError {}

/// In-memory effect handler for plugin tests (ADR-053 chunk 4).
///
/// `MockHandler` replaces the live host dispatcher with a recorded
/// program: each emitted effect is logged, then matched against a list
/// of rules in declaration order. The first matching rule decides whether
/// the effect succeeds (with a supplied [`EffectReply`]) or is rejected
/// (with a configurable [`EffectError`]). Effects that match no rule
/// default to `EffectReply::Unit`, so trivial fire-and-forget tests
/// require zero setup.
///
/// The handler implements [`Yielder`] directly, so it can be passed to
/// any [`Effectful::step`] call.
///
/// ```
/// use kasane_plugin_sdk::effects::{Effect, EffectError, EffectReply, MockHandler, Yielder};
///
/// let mut handler = MockHandler::new()
///     .respond(
///         |e| matches!(e, Effect::PasteClipboard),
///         EffectReply::ClipboardText("from-clipboard".into()),
///     )
///     .reject(
///         |e| matches!(e, Effect::SetClipboard(_)),
///         EffectError::Rejected("no clipboard authority in this test"),
///     );
///
/// assert_eq!(
///     handler.emit(Effect::PasteClipboard).unwrap(),
///     EffectReply::ClipboardText("from-clipboard".into()),
/// );
/// assert!(handler.emit(Effect::SetClipboard("x".into())).is_err());
/// assert_eq!(handler.emitted().len(), 2);
/// ```
pub struct MockHandler {
    rules: Vec<HandlerRule>,
    emitted: Vec<Effect>,
}

type EffectPredicate = Box<dyn Fn(&Effect) -> bool + Send + Sync>;

enum HandlerRule {
    Respond {
        predicate: EffectPredicate,
        reply: EffectReply,
    },
    Reject {
        predicate: EffectPredicate,
        error: EffectError,
    },
}

impl MockHandler {
    /// Build an empty handler. Any emit will succeed with `EffectReply::Unit`.
    pub fn new() -> Self {
        Self {
            rules: Vec::new(),
            emitted: Vec::new(),
        }
    }

    /// Match effects passing `predicate` and reply with `reply`. Rules are
    /// evaluated in declaration order — earlier rules win on overlap.
    pub fn respond<F>(mut self, predicate: F, reply: EffectReply) -> Self
    where
        F: Fn(&Effect) -> bool + Send + Sync + 'static,
    {
        self.rules.push(HandlerRule::Respond {
            predicate: Box::new(predicate),
            reply,
        });
        self
    }

    /// Match effects passing `predicate` and return `error` to the plugin
    /// — typically the path tests use to exercise the
    /// `?`-propagation arm of a lowered handler.
    pub fn reject<F>(mut self, predicate: F, error: EffectError) -> Self
    where
        F: Fn(&Effect) -> bool + Send + Sync + 'static,
    {
        self.rules.push(HandlerRule::Reject {
            predicate: Box::new(predicate),
            error,
        });
        self
    }

    /// Every effect the plugin emitted, in order, including ones that
    /// were rejected. Use this to assert the effect *sequence* a plugin
    /// produced under a given input.
    pub fn emitted(&self) -> &[Effect] {
        &self.emitted
    }

    /// Discard the recorded log without recreating the handler.
    pub fn clear(&mut self) {
        self.emitted.clear();
    }
}

impl Default for MockHandler {
    fn default() -> Self {
        Self::new()
    }
}

impl Yielder for MockHandler {
    type Effect = Effect;
    type Reply = EffectReply;
    type Error = EffectError;

    fn emit(&mut self, effect: Self::Effect) -> Result<Self::Reply, Self::Error> {
        self.emitted.push(effect.clone());
        for rule in &self.rules {
            match rule {
                HandlerRule::Respond { predicate, reply } if predicate(&effect) => {
                    return Ok(reply.clone());
                }
                HandlerRule::Reject { predicate, error } if predicate(&effect) => {
                    return Err(error.clone());
                }
                _ => {}
            }
        }
        Ok(EffectReply::Unit)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn capability_name_display_is_raw_string() {
        let cap = CapabilityName("filesystem");
        assert_eq!(cap.to_string(), "filesystem");
        assert_eq!(cap.as_str(), "filesystem");
    }

    #[test]
    fn capability_name_debug_shows_wrapper() {
        let cap = CapabilityName("process");
        assert_eq!(format!("{cap:?}"), r#"CapabilityName("process")"#);
    }

    #[test]
    fn effect_required_capabilities_covers_starter_set() {
        assert_eq!(Effect::Redraw(0).required_capabilities(), &[] as &[_]);
        assert_eq!(
            Effect::EvalCommand("echo".into()).required_capabilities(),
            &[] as &[_]
        );
        assert_eq!(
            Effect::SetClipboard("hi".into()).required_capabilities(),
            &[CapabilityName("clipboard")]
        );
        assert_eq!(
            Effect::PasteClipboard.required_capabilities(),
            &[CapabilityName("clipboard")]
        );
    }

    #[test]
    fn effect_error_display() {
        assert_eq!(
            EffectError::MissingCapability(CapabilityName("process")).to_string(),
            "missing capability: process"
        );
        assert_eq!(
            EffectError::Rejected("mocked").to_string(),
            "effect rejected: mocked"
        );
    }

    // Smoke test: a hand-written effect set + yielder + Effectful impl
    // compiles against the chunk 1 signatures. The macro will generate
    // analogous code in chunk 2; verifying the shape here pins the trait
    // surface before downstream code lands.
    mod smoke {
        use super::*;

        struct DemoEffects;
        impl Sealed for DemoEffects {}
        impl EffectSet for DemoEffects {
            type Yielder = DemoYielder;
            const REQUIRED_CAPABILITIES: &'static [CapabilityName] = &[];
        }

        struct DemoYielder {
            log: Vec<Effect>,
        }
        impl Yielder for DemoYielder {
            type Effect = Effect;
            type Reply = EffectReply;
            type Error = EffectError;

            fn emit(&mut self, effect: Self::Effect) -> Result<Self::Reply, Self::Error> {
                self.log.push(effect);
                Ok(EffectReply::Unit)
            }
        }

        struct DemoPlugin {
            steps: u32,
        }
        impl Effectful for DemoPlugin {
            type Effects = DemoEffects;
            fn step(
                &mut self,
                yielder: &mut <Self::Effects as EffectSet>::Yielder,
            ) -> EffectfulResult {
                self.steps += 1;
                match yielder.emit(Effect::EvalCommand("echo hi".into())) {
                    Ok(_) => EffectfulResult::Done,
                    Err(_) => EffectfulResult::Aborted,
                }
            }
        }

        #[test]
        fn handwritten_effect_set_drives_one_step() {
            let mut plugin = DemoPlugin { steps: 0 };
            let mut yielder = DemoYielder { log: Vec::new() };
            let result = plugin.step(&mut yielder);
            assert_eq!(result, EffectfulResult::Done);
            assert_eq!(plugin.steps, 1);
            assert_eq!(yielder.log, vec![Effect::EvalCommand("echo hi".into())]);
        }

        #[test]
        fn required_capabilities_is_visible_via_associated_const() {
            assert_eq!(
                <DemoEffects as EffectSet>::REQUIRED_CAPABILITIES,
                &[] as &[CapabilityName]
            );
        }
    }

    mod mock_handler {
        use super::*;

        #[test]
        fn default_handler_replies_unit_and_logs_effect() {
            let mut handler = MockHandler::new();
            let reply = handler.emit(Effect::Redraw(7)).unwrap();
            assert_eq!(reply, EffectReply::Unit);
            assert_eq!(handler.emitted(), &[Effect::Redraw(7)]);
        }

        #[test]
        fn respond_rule_matches_predicate_and_returns_supplied_reply() {
            let mut handler = MockHandler::new().respond(
                |e| matches!(e, Effect::PasteClipboard),
                EffectReply::ClipboardText("from-mock".into()),
            );
            let reply = handler.emit(Effect::PasteClipboard).unwrap();
            assert_eq!(reply, EffectReply::ClipboardText("from-mock".into()));
        }

        #[test]
        fn reject_rule_returns_supplied_error() {
            let mut handler = MockHandler::new().reject(
                |e| matches!(e, Effect::SetClipboard(_)),
                EffectError::Rejected("no clipboard authority"),
            );
            let err = handler.emit(Effect::SetClipboard("x".into())).unwrap_err();
            assert_eq!(err, EffectError::Rejected("no clipboard authority"));
        }

        #[test]
        fn rules_evaluate_in_declaration_order() {
            // Two overlapping rules: the first should win on PasteClipboard.
            let mut handler = MockHandler::new()
                .respond(
                    |e| matches!(e, Effect::PasteClipboard),
                    EffectReply::ClipboardText("first".into()),
                )
                .respond(|_| true, EffectReply::ClipboardText("catch-all".into()));
            let reply = handler.emit(Effect::PasteClipboard).unwrap();
            assert_eq!(reply, EffectReply::ClipboardText("first".into()));
        }

        #[test]
        fn unmatched_effects_fall_through_to_unit_reply() {
            let mut handler = MockHandler::new().reject(
                |e| matches!(e, Effect::SetClipboard(_)),
                EffectError::Rejected("nope"),
            );
            // PasteClipboard doesn't match the reject rule; falls through.
            let reply = handler.emit(Effect::PasteClipboard).unwrap();
            assert_eq!(reply, EffectReply::Unit);
        }

        #[test]
        fn emitted_log_preserves_order_including_rejected_effects() {
            let mut handler = MockHandler::new().reject(
                |e| matches!(e, Effect::SetClipboard(_)),
                EffectError::Rejected("no"),
            );
            let _ = handler.emit(Effect::Redraw(0));
            let _ = handler.emit(Effect::SetClipboard("a".into()));
            let _ = handler.emit(Effect::EvalCommand("echo".into()));
            assert_eq!(
                handler.emitted(),
                &[
                    Effect::Redraw(0),
                    Effect::SetClipboard("a".into()),
                    Effect::EvalCommand("echo".into()),
                ]
            );
        }

        #[test]
        fn clear_empties_log_without_dropping_rules() {
            let mut handler =
                MockHandler::new().respond(|_| true, EffectReply::ClipboardText("hi".into()));
            let _ = handler.emit(Effect::PasteClipboard);
            handler.clear();
            assert!(handler.emitted().is_empty());
            // Rule still active:
            let reply = handler.emit(Effect::PasteClipboard).unwrap();
            assert_eq!(reply, EffectReply::ClipboardText("hi".into()));
        }
    }
}
