//! `#[derive(DirtyTracked)]` — compile-time enforcement of field → DirtyFlags mapping.
//!
//! Every field in the annotated struct must carry exactly one of:
//! - `#[dirty(FLAG1, FLAG2, ...)]` — this field requires the listed DirtyFlags
//! - `#[dirty(free)]` — this field is a free read (no DirtyFlag needed)
//!
//! The derive generates two public constants:
//! - `FIELD_DIRTY_MAP: &[(&str, &[&str])]` — field→flags for tracked fields
//! - `FREE_READ_FIELDS: &[&str]` — field names marked as free reads

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Error, Fields, Ident, Meta};

/// Parsed dirty annotation for one field.
enum DirtyAnnotation {
    /// `#[dirty(FLAG1, FLAG2, ...)]`
    Flags(Vec<String>),
    /// `#[dirty(free)]`
    Free,
}

pub fn expand_dirty_tracked(input: TokenStream) -> syn::Result<TokenStream> {
    let input: DeriveInput = syn::parse2(input)?;

    let Data::Struct(data_struct) = &input.data else {
        return Err(Error::new_spanned(
            &input.ident,
            "DirtyTracked can only be derived on structs",
        ));
    };

    let Fields::Named(fields) = &data_struct.fields else {
        return Err(Error::new_spanned(
            &input.ident,
            "DirtyTracked requires named fields",
        ));
    };

    let known_flags: &[&str] = &[
        "BUFFER_CONTENT",
        "BUFFER_CURSOR",
        "STATUS",
        "MENU_STRUCTURE",
        "MENU_SELECTION",
        "INFO",
        "OPTIONS",
        "SESSION",
    ];

    let mut field_entries = Vec::new(); // (field_name, &[flag_names])
    let mut free_fields = Vec::new(); // field_name

    for field in &fields.named {
        let field_name = field
            .ident
            .as_ref()
            .ok_or_else(|| Error::new_spanned(field, "expected named field"))?;

        let annotation = parse_dirty_attr(field_name, &field.attrs)?;
        let Some(annotation) = annotation else {
            return Err(Error::new_spanned(
                field_name,
                format!(
                    "field `{}` is missing a `#[dirty(...)]` annotation. \
                     Add `#[dirty(FLAG)]` or `#[dirty(free)]`",
                    field_name
                ),
            ));
        };

        match annotation {
            DirtyAnnotation::Flags(flags) => {
                // Validate flag names
                for flag in &flags {
                    if !known_flags.contains(&flag.as_str()) {
                        return Err(Error::new_spanned(
                            field_name,
                            format!(
                                "unknown DirtyFlags variant `{flag}` in #[dirty(...)]. \
                                 Expected one of: {}",
                                known_flags.join(", ")
                            ),
                        ));
                    }
                }
                field_entries.push((field_name.to_string(), flags));
            }
            DirtyAnnotation::Free => {
                free_fields.push(field_name.to_string());
            }
        }
    }

    // Generate the FIELD_DIRTY_MAP constant
    let map_entries = field_entries.iter().map(|(name, flags)| {
        let flag_strs = flags.iter().map(|f| quote! { #f });
        quote! { (#name, &[#(#flag_strs),*] as &[&str]) }
    });

    let free_entries = free_fields.iter().map(|name| {
        quote! { #name }
    });

    let struct_name = &input.ident;

    // We generate an impl block with associated constants
    let expanded = quote! {
        impl #struct_name {
            /// Field → DirtyFlags mapping, generated by `#[derive(DirtyTracked)]`.
            ///
            /// Each entry is `(field_name, &[flag_names])`. Fields marked
            /// `#[dirty(free)]` are excluded (they appear in `FREE_READ_FIELDS`).
            pub const FIELD_DIRTY_MAP: &[(&str, &[&str])] = &[
                #(#map_entries),*
            ];

            /// Fields that are free reads (no DirtyFlag needed).
            pub const FREE_READ_FIELDS: &[&str] = &[
                #(#free_entries),*
            ];
        }
    };

    Ok(expanded)
}

/// Parse the `#[dirty(...)]` attribute from a field's attributes.
fn parse_dirty_attr(
    field_name: &Ident,
    attrs: &[syn::Attribute],
) -> syn::Result<Option<DirtyAnnotation>> {
    let dirty_attrs: Vec<_> = attrs
        .iter()
        .filter(|a| a.path().is_ident("dirty"))
        .collect();

    if dirty_attrs.is_empty() {
        return Ok(None);
    }

    if dirty_attrs.len() > 1 {
        return Err(Error::new_spanned(
            field_name,
            "multiple #[dirty(...)] annotations on the same field",
        ));
    }

    let attr = dirty_attrs[0];

    let Meta::List(meta_list) = &attr.meta else {
        return Err(Error::new_spanned(
            attr,
            "expected #[dirty(FLAG, ...)] or #[dirty(free)]",
        ));
    };

    let tokens: Vec<proc_macro2::TokenTree> = meta_list.tokens.clone().into_iter().collect();

    if tokens.is_empty() {
        return Err(Error::new_spanned(
            attr,
            "empty #[dirty()]: specify flag names or `free`",
        ));
    }

    // Check for `free`
    if tokens.len() == 1
        && let proc_macro2::TokenTree::Ident(ref ident) = tokens[0]
        && ident == "free"
    {
        return Ok(Some(DirtyAnnotation::Free));
    }

    // Parse comma-separated flag identifiers
    let mut flags = Vec::new();
    let mut expect_ident = true;
    for token in &tokens {
        match token {
            proc_macro2::TokenTree::Ident(ident) if expect_ident => {
                if ident == "free" {
                    return Err(Error::new_spanned(
                        ident,
                        "`free` cannot be combined with flag names",
                    ));
                }
                flags.push(ident.to_string());
                expect_ident = false;
            }
            proc_macro2::TokenTree::Punct(p) if !expect_ident && p.as_char() == ',' => {
                expect_ident = true;
            }
            other => {
                return Err(Error::new_spanned(
                    other,
                    "expected flag name or comma in #[dirty(...)]",
                ));
            }
        }
    }

    if flags.is_empty() {
        return Err(Error::new_spanned(
            attr,
            "#[dirty()] must contain at least one flag name or `free`",
        ));
    }

    Ok(Some(DirtyAnnotation::Flags(flags)))
}
