use crate::element::Overlay;
use crate::layout::Rect;
use crate::layout::flex;
use crate::plugin::EffectiveSectionDeps;
use crate::state::DirtyFlags;
use crate::surface::SurfaceComposeResult;

// ---------------------------------------------------------------------------
// ComponentCache — generic memoization wrapper for component functions
// ---------------------------------------------------------------------------

/// Generic cache for a component function's return value.
/// Used by macro-generated `_cached` wrappers to skip recomputation
/// when the relevant DirtyFlags are not set.
#[derive(Debug, Clone)]
pub struct ComponentCache<T: Clone> {
    pub value: Option<T>,
}

impl<T: Clone> Default for ComponentCache<T> {
    fn default() -> Self {
        Self { value: None }
    }
}

impl<T: Clone> ComponentCache<T> {
    pub fn new() -> Self {
        Self::default()
    }

    /// Get the cached value, or compute and cache it.
    /// `deps` is the DirtyFlags mask for this component.
    /// Returns the cached value if `dirty` does not intersect `deps`.
    pub fn get_or_insert(
        &mut self,
        dirty: DirtyFlags,
        deps: DirtyFlags,
        compute: impl FnOnce() -> T,
    ) -> T {
        if !dirty.intersects(deps)
            && let Some(ref cached) = self.value
        {
            return cached.clone();
        }
        let val = compute();
        self.value = Some(val.clone());
        val
    }

    /// Invalidate the cached value if dirty flags intersect deps.
    pub fn invalidate(&mut self, dirty: DirtyFlags, deps: DirtyFlags) {
        if dirty.intersects(deps) {
            self.value = None;
        }
    }
}

// ---------------------------------------------------------------------------
// ViewCache — subtree memoization for view()
// ---------------------------------------------------------------------------

/// Cache for memoized view subtrees. Each field stores the result of a view
/// section so it can be reused when the corresponding DirtyFlags are not set.
///
/// Uses `ComponentCache<T>` internally, with invalidation masks matching the
/// DEPS constants generated by `#[kasane_component]`.
#[derive(Debug, Default)]
pub struct ViewCache {
    /// Base layout: buffer + status bar + plugin slots.
    pub(crate) base: ComponentCache<SurfaceComposeResult>,
    /// Menu overlay.
    pub(crate) menu_overlay: ComponentCache<Option<Overlay>>,
    /// Info overlays.
    pub(crate) info_overlays: ComponentCache<Vec<Overlay>>,
}

impl ViewCache {
    pub fn new() -> Self {
        Self::default()
    }

    /// Invalidate cached sections based on which flags are dirty.
    ///
    /// Uses fixed deps masks matching the core DEPS constants. For dynamic
    /// deps that account for plugin contributions, use `invalidate_with_deps()`.
    pub fn invalidate(&mut self, dirty: DirtyFlags) {
        // These masks match the DEPS constants in view/mod.rs:
        //   BUILD_BASE_DEPS = BUFFER_CONTENT | STATUS | OPTIONS
        //   BUILD_MENU_SECTION_DEPS = MENU_STRUCTURE | MENU_SELECTION | OPTIONS
        //   BUILD_INFO_SECTION_DEPS = INFO | OPTIONS
        self.base.invalidate(
            dirty,
            DirtyFlags::BUFFER_CONTENT | DirtyFlags::STATUS | DirtyFlags::OPTIONS,
        );
        self.menu_overlay
            .invalidate(dirty, DirtyFlags::MENU | DirtyFlags::OPTIONS);
        self.info_overlays
            .invalidate(dirty, DirtyFlags::INFO | DirtyFlags::OPTIONS);
    }

    /// Invalidate cached sections using dynamic deps from plugin contributions.
    pub fn invalidate_with_deps(&mut self, dirty: DirtyFlags, deps: &EffectiveSectionDeps) {
        self.base.invalidate(dirty, deps.base);
        self.menu_overlay.invalidate(dirty, deps.menu);
        self.info_overlays.invalidate(dirty, deps.info);
    }
}

// ---------------------------------------------------------------------------
// LayoutCache — cached layout positions for section-level repaint
// ---------------------------------------------------------------------------

/// Cache for layout positions so that section-level repaints can target the
/// correct grid region without a full layout pass.
#[derive(Debug, Default)]
pub struct LayoutCache {
    /// Cached base layout result.
    pub(crate) base_layout: Option<flex::LayoutResult>,
    /// Y position of the status bar row.
    pub(crate) status_row: Option<u16>,
    /// Root area used for the last layout.
    pub(crate) root_area: Option<Rect>,
}

impl LayoutCache {
    pub fn new() -> Self {
        Self::default()
    }

    /// Invalidate cached layout based on dirty flags and resize.
    pub fn invalidate(&mut self, dirty: DirtyFlags, cols: u16, rows: u16) {
        // Resize → clear everything
        if let Some(root) = self.root_area
            && (root.w != cols || root.h != rows)
        {
            self.base_layout = None;
            self.status_row = None;
            self.root_area = None;
            return;
        }
        if dirty.intersects(DirtyFlags::BUFFER_CONTENT | DirtyFlags::STATUS | DirtyFlags::OPTIONS) {
            self.base_layout = None;
            self.status_row = None;
        }
    }
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

/// Helper to determine if a ComponentCache needs recomputation.
/// Returns ALL if the cache is empty (cold), or empty if cached (warm).
/// The actual dirty flags from update() are handled by ViewCache::invalidate()
/// which clears the ComponentCache::value when relevant flags are set.
pub(crate) fn cache_dirty_snapshot<T: Clone>(
    cache: &ComponentCache<T>,
    deps: DirtyFlags,
) -> DirtyFlags {
    if cache.value.is_none() {
        deps // Force recomputation
    } else {
        DirtyFlags::empty() // Use cached value
    }
}
